apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: nrc-plugin-cert
  labels:
    app: node-remediation-console-plugin
  name: node-remediation-console-plugin
  namespace: openshift-operators
spec:
  ports:
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: nrc-server
  selector:
    app: node-remediation-console-plugin
  sessionAffinity: None
  type: ClusterIP
